### ISSUE TITLE
[Help Wanted]: "Muse Dash.exe is not correct version"

### ISSUE THREAD

**Issue by kkkkanna** [MDModsDev/MuseDashModToolsUI#52]
### Operating system

Other Linux distribution

### Problem Detail (Optional)

help
i didnt pirate the game
i dont know why this happens

### Screenshots (Optional)

![Screenshot_20230806_085238](https://github.com/MDModsDev/MuseDashModToolsUI/assets/103551093/c97c42d7-6678-4b6d-9f23-ebcdd7b763eb)

### Logs

[2023-08-06_08-53-14.log](https://github.com/MDModsDev/MuseDashModToolsUI/files/12269643/2023-08-06_08-53-14.log)

**Comment by lxymahatma** [comment]
> 

hmm i'm not sure why it's happening because i use windows to develop the app, it seems like you have chosen the path before, and the second time you run the app it crashed?
in the log it says `[08:53:15.841 -04:00] [Information]
Get current version success: null`, and i also didnt see the version number on the right top of the window
so i'm not sure whether it's a linux problem or you downloaded the wrong release, can you check you have downloaded the latest 1.2.0 release?

the following are explanations of log errors:`System.ArgumentException: The directory name '/home/gabriel/.local/share/Steam/steamapps/common/Muse Dash/Mods' does not exist. (Parameter 'Path')` means it didnt find the Mods folder when the code executes, so i dont know if you can manually create one to make the app work

also, i save the Settings.json file, which is the setting file for the application in home/.config folder (you can find a folder called MuseDashModTools in it according to the article https://developers.redhat.com/blog/2018/11/07/dotnet-special-folder-api-linux. so if you cannot solve the problem, and the first launch is success (i assume you have chosen the path in first launch because that's what i understand from log file), then you can try delete the Settings.json and choose the file again

i hope the above information helps 👀

**Comment by lxymahatma** [comment]
If the above doesnt solve the problem can you try downloading this https://github.com/MDModsDev/MuseDashModToolsUI/suites/14862823692/artifacts/846409640
I've added some log information for checking which part is wrong
so you launch that version and upload the log file to here
